provisioner:
  hosts:
    localhost:
  vars:

### USER VARIABLES ###

    # Deployment node interface name for the lab public conneciton
    pub_if: 

    # Deployment node interface name for the "baremetal" connection
    bm_if: 

    # Username for IPMI connections
    ipmi_user: 

    # Password for IPMI connections
    ipmi_password: 

    # Cluster node interfaces to disable (list)
    ifs_disable:
      - 

    # Cluster master node FQDNs as defined by in the lab environment (NOT "master-0")
    # THREE REQUIRED
    master_fqdns:
      - 
      - 
      - 

    # Cluster master node MAC addresses for baremetal interfaces (list)
    # THREE REQUIRED
    master_bm_macs:
      - 
      - 
      - 

    # Cluster master node MAC addresses for provisioning ("director") interfaces (list)
    # THREE REQUIRED
    master_prov_macs:
      - 
      - 
      - 


### CONVENIENCE VARIABLES ###

    # Yum packages to install (list)
    yum_packages:
      - dnsmasq
      - python3-dns
      - podman

    # Badfish pod image
    badfish_pod_image: quads/badfish

    # Badfish podman base command
    badfish_cmd: "podman run -it --rm {{ badfish_pod_image }} -u {{ ipmi_user }} -p {{ ipmi_password }} -i config/idrac_interfaces.yml -H mgmt-"
